-- Sample notes for user_id 0
INSERT INTO notes (user_id, title, content, created_at) VALUES
(0, 'Weekend To-Do List', 'Hereâ€™s the plan for the weekend: \n- Saturday: 1. Morning: Visit the farmers'' market. 2. Afternoon: Organize the bookshelf and donate old books. 3. Evening: Try a new recipe for dinner. \n- Sunday: 1. Morning: Go for a run in the park. 2. Afternoon: Call parents and catch up. 3. Evening: Watch a documentary.', CURRENT_TIMESTAMP),
(0, 'Grocery Shopping List', 'Items to buy for this week: \n- Fruits: Apples, Bananas, Strawberries \n- Vegetables: Spinach, Carrots, Broccoli \n- Dairy: Milk, Cheese, Yogurt \n- Meat: Chicken breasts, Salmon \n- Snacks: Almonds, Dark chocolate, Granola bars \n- Misc: Olive oil, Garlic, Canned beans', CURRENT_TIMESTAMP),
(0, 'Recipe: Chicken Caesar Salad', 'A simple and healthy meal idea: \n- Ingredients: \n  - 2 chicken breasts \n  - Romaine lettuce \n  - Caesar dressing \n  - Croutons \n  - Shredded parmesan cheese \n- Instructions: \n 1. Grill chicken breasts and slice them. \n 2. Toss lettuce with Caesar dressing, croutons, and parmesan. \n 3. Top with grilled chicken and enjoy!', CURRENT_TIMESTAMP),
(0, 'Travel Bucket List', 'Places to visit someday: \n- Paris, France: Explore the Eiffel Tower and Louvre Museum. \n- Tokyo, Japan: Visit Shibuya Crossing and try sushi. \n- New York City, USA: Walk through Central Park and see a Broadway show. \n- Sydney, Australia: Bondi Beach and Sydney Opera House.', CURRENT_TIMESTAMP),
(0, 'Fitness Goals for the Month', 'This month''s focus: \n- Week 1: Cardio (30-minute runs 3 times a week) \n- Week 2: Strength training (full body, 3 times a week) \n- Week 3: Flexibility (yoga sessions 3 times a week) \n- Week 4: Endurance (try a 10K run)', CURRENT_TIMESTAMP);

-- Sample notes for user_id 1
INSERT INTO notes (user_id, title, content, created_at) VALUES
(1, 'Recipe: Vegan Buddha Bowl', 'A nutritious and filling vegan meal: \n- Ingredients: \n  - Quinoa \n  - Roasted sweet potatoes \n  - Avocado \n  - Chickpeas \n  - Kale \n  - Tahini dressing \n- Instructions: \n 1. Cook quinoa and roast sweet potatoes. \n 2. Sauté kale and heat chickpeas. \n 3. Assemble all ingredients in a bowl and drizzle with tahini dressing.', CURRENT_TIMESTAMP),
(1, 'Morning Routine', 'Start the day right: \n- Wake up at 6:30 AM \n- Drink a glass of water \n- 10-minute morning stretch \n- Breakfast: Oats with almond butter and chia seeds \n- Meditate for 5 minutes \n- Review daily goals and tasks', CURRENT_TIMESTAMP),
(1, 'Books to Read This Year', 'Books I want to read: \n- "The Catcher in the Rye" by J.D. Salinger \n- "Sapiens: A Brief History of Humankind" by Yuval Noah Harari \n- "The Great Gatsby" by F. Scott Fitzgerald \n- "Atomic Habits" by James Clear \n- "Educated" by Tara Westover', CURRENT_TIMESTAMP);
